// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA45piSGpi3lT46Pslz4rH16zIM5trYPY',
    appId: '1:949941112705:android:7f67f2afa7babc8cfb2280',
    messagingSenderId: '949941112705',
    projectId: 'mobux-d8860',
    databaseURL: 'https://mobux-d8860.firebaseio.com',
    storageBucket: 'mobux-d8860.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCGC5a2b5wcBEeQP4nMVLyiPQrFCWoiA',
    appId: '1:949941112705:ios:baa010eb35338979fb2280',
    messagingSenderId: '949941112705',
    projectId: 'mobux-d8860',
    databaseURL: 'https://mobux-d8860.firebaseio.com',
    storageBucket: 'mobux-d8860.appspot.com',
    iosClientId: '949941112705-529eqkq2e8j6jtg4vs13oh8k43gjilk7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCli',
  );
}
